name: build and run test

on:
  push:
      branches:
        - master

jobs:
  test-and-rebase:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1 # 需要完整提交历史用于变基

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc make

    - name: Run build
      run: |
        cd example
        make

    - name: test project
      run: |
        cd example
        make test
